-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3333
-- Время создания: Июн 23 2022 г., 18:47
-- Версия сервера: 8.0.29
-- Версия PHP: 8.1.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `blog_db`
--

-- --------------------------------------------------------

--
-- Структура таблицы `blog_tb`
--

CREATE TABLE `blog_tb` (
  `id` int NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL,
  `content` text CHARACTER SET utf8mb3 COLLATE utf8_general_ci,
  `author` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL,
  `tags` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Дамп данных таблицы `blog_tb`
--

INSERT INTO `blog_tb` (`id`, `title`, `content`, `author`, `tags`, `date`, `image`) VALUES
(1, 'Cake Milk girl', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Kalashnikov Austin Lvovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 03:11:04', 'images/tort1.jpg'),
(2, 'Chocolate cake \"Glass\" with cottage cheese', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Baranov Prokhor Vladimirovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 03:16:44', 'images/tort2.jpg'),
(3, 'Cake \"Biscuit Miracle\"', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Andrukhovych Ludovik Dmitrievich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 03:21:14', 'images/tort3.jpg'),
(4, 'Cake \"Snickers\"', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Lazarev Tit Vasilievich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 04:34:30', 'images/tort4.jpg'),
(5, 'Biscuit cake with ice cream', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Eremenko Yulian Sergeevich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:35:51', 'images/tort5.jpg'),
(6, 'Medovik (without rolling cakes)', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Frolov Cheslav Bogdanovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:39:04', 'images/tort6.jpg'),
(7, 'Cake Red value', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Ignatov Mikhail Romanovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:43:25', 'images/tort7.jpg'),
(8, 'Chocolate cake', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Chernov Gerasim Yaroslavovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:44:58', 'images/tort8.jpg'),
(9, 'Mousse chocolate cake with bananas', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Povaliy Lukillian Eduardovich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:46:35', 'images/tort9.jpg'),
(10, 'Cake Spartacus', 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat nesciunt magnam itaque cumque laborum quis recusandae sunt cum dicta consequuntur! Iusto cumque reprehenderit, id distinctio perferendis non sapiente modi! A?', 'Peredriy Dinar Valerievich', 'cakes, sugar, cake, obesity, sweets', '2022-06-23 13:48:10', 'images/tort10.jpg');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `blog_tb`
--
ALTER TABLE `blog_tb`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `blog_tb`
--
ALTER TABLE `blog_tb`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
